"""Compare extracted Sedon and Open Duck Mini parameter snapshots."""

from __future__ import annotations

import argparse
from pathlib import Path
from typing import Any

from tools.sedon.extractors.robot_parameter_common import ExtractionError, read_yaml_compatible_json

REPO_ROOT = Path(__file__).resolve().parents[3]
DEFAULT_SEDON_YAML = REPO_ROOT / "configs" / "sedon" / "sedon_robot_parameters.yaml"
DEFAULT_DUCK_YAML = REPO_ROOT / "references" / "open_duck_mini" / "duck_robot_parameters.yaml"
DEFAULT_OUTPUT = REPO_ROOT / "docs" / "sedon_duck_comparison.md"


def build_parser() -> argparse.ArgumentParser:
    """Build the CLI parser."""

    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("--sedon-yaml", type=Path, default=DEFAULT_SEDON_YAML)
    parser.add_argument("--duck-yaml", type=Path, default=DEFAULT_DUCK_YAML)
    parser.add_argument("--output", type=Path, default=DEFAULT_OUTPUT)
    return parser


def by_name(records: list[dict[str, Any]]) -> dict[str, dict[str, Any]]:
    """Index records by name."""

    return {str(record.get("name", "unknown")): record for record in records}


def names(records: list[dict[str, Any]]) -> list[str]:
    """Return sorted record names."""

    return sorted(str(record.get("name", "unknown")) for record in records)


def field_table(
    sedon_records: list[dict[str, Any]],
    duck_records: list[dict[str, Any]],
    fields: tuple[str, ...],
    limit: int = 40,
) -> list[str]:
    """Build a markdown table comparing records by exact name."""

    sedon = by_name(sedon_records)
    duck = by_name(duck_records)
    all_names = sorted(set(sedon) | set(duck))
    lines = [
        "| Name | In Sedon | In Duck | " + " | ".join(f"Sedon {field} / Duck {field}" for field in fields) + " |",
        "|---|---|---|" + "---|" * len(fields),
    ]
    for name in all_names[:limit]:
        sedon_row = sedon.get(name)
        duck_row = duck.get(name)
        values = []
        for field in fields:
            values.append(f"`{sedon_row.get(field) if sedon_row else 'unknown'}` / `{duck_row.get(field) if duck_row else 'unknown'}`")
        lines.append(f"| `{name}` | {sedon_row is not None} | {duck_row is not None} | " + " | ".join(values) + " |")
    if len(all_names) > limit:
        lines.append(f"| ... | ... | ... | truncated {len(all_names) - limit} additional rows |")
    return lines


def possible_scale_notes(sedon: dict[str, Any], duck: dict[str, Any]) -> list[str]:
    """Return conservative scale comparison notes.

    The extractor does not compile MuJoCo or compute world-frame dimensions, so
    this reports only fields that can be compared directly from explicit XML.
    """

    sedon_mass = sedon.get("summary", {}).get("total_explicit_body_mass")
    duck_mass = duck.get("summary", {}).get("total_explicit_body_mass")
    notes = [f"- total explicit body mass: Sedon `{sedon_mass}`, Duck `{duck_mass}`"]
    if isinstance(sedon_mass, (int, float)) and isinstance(duck_mass, (int, float)) and duck_mass:
        notes.append(f"- explicit mass ratio Sedon/Duck: `{sedon_mass / duck_mass:.6f}`")
    else:
        notes.append("- explicit mass ratio Sedon/Duck: `unknown`")

    sedon_foot_sizes = [geom.get("size") for geom in sedon.get("foot_related", {}).get("geoms", []) if geom.get("size")]
    duck_foot_sizes = [geom.get("size") for geom in duck.get("foot_related", {}).get("geoms", []) if geom.get("size")]
    notes.append(f"- Sedon explicit foot geom sizes: `{sedon_foot_sizes or 'unknown'}`")
    notes.append(f"- Duck explicit foot geom sizes: `{duck_foot_sizes or 'unknown'}`")
    notes.append("- leg length and world-frame foot scale: `unknown` in this XML-only comparison")
    return notes


def write_comparison(path: Path, sedon: dict[str, Any], duck: dict[str, Any]) -> None:
    """Write Sedon vs Duck markdown comparison."""

    sedon_counts = sedon.get("counts", {})
    duck_counts = duck.get("counts", {})
    lines = [
        "# Sedon vs Open Duck Mini Parameter Comparison",
        "",
        "Generated by `tools.sedon.extractors.compare_sedon_duck_parameters`.",
        "",
        "## Sources",
        "",
        f"- Sedon YAML: `{sedon.get('source_xml', 'unknown')}`",
        f"- Duck YAML: `{duck.get('source_xml', 'unknown')}`",
        f"- Sedon extracted_at: `{sedon.get('extracted_at', 'unknown')}`",
        f"- Duck extracted_at: `{duck.get('extracted_at', 'unknown')}`",
        "",
        "## Count Comparison",
        "",
        "| Field | Sedon | Duck |",
        "|---|---:|---:|",
    ]
    for field in ("bodies", "joints", "geoms", "actuators", "foot_related_geoms"):
        lines.append(f"| {field} | {sedon_counts.get(field, 'unknown')} | {duck_counts.get(field, 'unknown')} |")

    lines.extend(
        [
            "",
            "## Joint Name / Axis / Range Comparison",
            "",
            *field_table(sedon.get("joints", []), duck.get("joints", []), ("axis", "range", "type")),
            "",
            "## Actuator Field Comparison",
            "",
            *field_table(sedon.get("actuators", []), duck.get("actuators", []), ("kind", "joint", "kp", "ctrlrange", "forcerange")),
            "",
            "## Foot-Related Geoms",
            "",
            "### Sedon",
            "",
            *(f"- `{name}`" for name in names(sedon.get("foot_related", {}).get("geoms", []))),
            "",
            "### Duck",
            "",
            *(f"- `{name}`" for name in names(duck.get("foot_related", {}).get("geoms", []))),
            "",
            "## Possible Scale Fields",
            "",
            *possible_scale_notes(sedon, duck),
            "",
            "## Fields Not Safe To Directly Transfer",
            "",
            "- Joint names and signs may differ even when semantic labels look similar.",
            "- Joint ranges are mechanical references, not action limits for policy transfer.",
            "- Actuator `kp`, `ctrlrange`, and `forcerange` depend on actuator type and control semantics.",
            "- Foot geoms use name heuristics; contact patch semantics require simulation validation.",
            "- Duck gait parameters should be used as reference targets, not copied as Sedon actions.",
        ]
    )
    path.parent.mkdir(parents=True, exist_ok=True)
    path.write_text("\n".join(lines) + "\n", encoding="utf-8")


def main(argv: list[str] | None = None) -> int:
    """Run Sedon vs Duck comparison."""

    args = build_parser().parse_args(argv)
    try:
        sedon = read_yaml_compatible_json(args.sedon_yaml)
        duck = read_yaml_compatible_json(args.duck_yaml)
        write_comparison(args.output, sedon, duck)
    except ExtractionError as exc:
        print(f"Sedon/Duck comparison failed: {exc}")
        return 2

    print(f"wrote_comparison={args.output}")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
