"""Extract explicit Sedon robot parameters from the committed private MJCF scene.

This Class C extractor is intentionally read-only with respect to the source
scene and training code. It parses the MJCF XML, writes a parameter snapshot,
and produces a compact index for later Duck-like gait reference work.
"""

from __future__ import annotations

import argparse
from pathlib import Path
from typing import Any

from tools.sedon.extractors.robot_parameter_common import (
    ExtractionError,
    compact_names,
    extract_robot_parameters,
    missing_field_names,
    write_yaml_compatible_json,
)

REPO_ROOT = Path(__file__).resolve().parents[3]
DEFAULT_SCENE = REPO_ROOT / "private_assets" / "sedon" / "training_scene.xml"
DEFAULT_OUTPUT_YAML = REPO_ROOT / "configs" / "sedon" / "sedon_robot_parameters.yaml"
DEFAULT_REPORT = REPO_ROOT / "docs" / "sedon_parameter_index.md"


def build_parser() -> argparse.ArgumentParser:
    """Build the CLI parser."""

    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("--scene", "--scene-path", type=Path, default=DEFAULT_SCENE)
    parser.add_argument("--output-yaml", type=Path, default=DEFAULT_OUTPUT_YAML)
    parser.add_argument("--report", type=Path, default=DEFAULT_REPORT)
    return parser


def write_report(path: Path, parameters: dict[str, Any], output_yaml: Path) -> None:
    """Write the Sedon parameter index report.

    Args:
        path: Report path.
        parameters: Extracted parameter payload.
        output_yaml: YAML snapshot path referenced by the report.
    """

    counts = parameters["counts"]
    summary = parameters["summary"]
    joints = parameters["joints"]
    actuators = parameters["actuators"]
    foot_geoms = parameters["foot_related"]["geoms"]
    missing_joint_ranges = missing_field_names(joints, "range")
    missing_actuator_kp = missing_field_names(actuators, "kp")
    missing_force_ranges = missing_field_names(actuators, "forcerange")

    lines = [
        "# Sedon Parameter Index",
        "",
        "Generated by `tools.sedon.extractors.extract_sedon_parameters`.",
        "",
        "## Source",
        "",
        f"- source_xml: `{parameters['source_xml']}`",
        f"- output_yaml: `{output_yaml}`",
        f"- extracted_at: `{parameters['extracted_at']}`",
        f"- tool_version: `{parameters['tool_version']}`",
        "",
        "## Counts",
        "",
        "| Field | Count |",
        "|---|---:|",
        f"| bodies | {counts['bodies']} |",
        f"| joints | {counts['joints']} |",
        f"| geoms | {counts['geoms']} |",
        f"| actuators | {counts['actuators']} |",
        f"| foot-related geoms | {counts['foot_related_geoms']} |",
        "",
        "## Mass / Inertia",
        "",
        f"- explicit body mass count: `{summary['body_mass_count']}`",
        f"- total explicit body mass: `{summary['total_explicit_body_mass']}`",
        "- compiled/default inertia values are not inferred by this extractor.",
        "",
        "## Joints",
        "",
        "| Name | Body | Type | Axis | Range | Actuator force range |",
        "|---|---|---|---|---|---|",
    ]
    for joint in joints:
        lines.append(
            f"| `{joint['name']}` | `{joint['body']}` | `{joint['type']}` | "
            f"`{joint['axis']}` | `{joint['range']}` | `{joint['actuatorfrcrange']}` |"
        )

    lines.extend(
        [
            "",
            "## Actuators",
            "",
            "| Name | Kind | Joint | kp | ctrlrange | forcerange |",
            "|---|---|---|---|---|---|",
        ]
    )
    for actuator in actuators:
        lines.append(
            f"| `{actuator['name']}` | `{actuator['kind']}` | `{actuator['joint']}` | "
            f"`{actuator['kp']}` | `{actuator['ctrlrange']}` | `{actuator['forcerange']}` |"
        )

    lines.extend(
        [
            "",
            "## Foot-Related Geoms",
            "",
            "| Name | Body | Type | Pos | Size | Friction | Side |",
            "|---|---|---|---|---|---|---|",
        ]
    )
    for geom in foot_geoms:
        lines.append(
            f"| `{geom['name']}` | `{geom['body']}` | `{geom['type']}` | "
            f"`{geom['pos']}` | `{geom['size']}` | `{geom['friction']}` | `{geom['side']}` |"
        )

    lines.extend(
        [
            "",
            "## Unknown / Null Fields",
            "",
            f"- joints without explicit range: `{compact_names([{'name': name} for name in missing_joint_ranges])}`",
            f"- actuators without explicit kp: `{missing_actuator_kp}`",
            f"- actuators without explicit forcerange: `{missing_force_ranges}`",
            "- Missing source attributes are represented as `null` in the YAML snapshot.",
            "",
            "## Notes",
            "",
            "- Foot-related records are selected by name heuristic: foot/toe/heel/sole/ankle/bottom.",
            "- Do not directly transfer Duck joint values into Sedon from this index; use it as reference data only.",
        ]
    )
    path.parent.mkdir(parents=True, exist_ok=True)
    path.write_text("\n".join(lines) + "\n", encoding="utf-8")


def main(argv: list[str] | None = None) -> int:
    """Run Sedon parameter extraction."""

    args = build_parser().parse_args(argv)
    try:
        parameters = extract_robot_parameters(args.scene, "sedon")
        write_yaml_compatible_json(args.output_yaml, parameters)
        write_report(args.report, parameters, args.output_yaml)
    except ExtractionError as exc:
        print(f"Sedon parameter extraction failed: {exc}")
        return 2

    counts = parameters["counts"]
    print(f"wrote_yaml={args.output_yaml}")
    print(f"wrote_report={args.report}")
    print(
        "sedon_counts bodies={bodies} joints={joints} geoms={geoms} actuators={actuators} foot_geoms={foot_geoms}".format(
            bodies=counts["bodies"],
            joints=counts["joints"],
            geoms=counts["geoms"],
            actuators=counts["actuators"],
            foot_geoms=counts["foot_related_geoms"],
        )
    )
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
