"""Extract Open Duck Mini robot parameters from a MuJoCo XML file."""

from __future__ import annotations

import argparse
from pathlib import Path
from typing import Any

from tools.sedon.extractors.robot_parameter_common import (
    TOOL_VERSION,
    ExtractionError,
    extract_robot_parameters,
    missing_field_names,
    utc_now_iso,
    write_yaml_compatible_json,
)

REPO_ROOT = Path(__file__).resolve().parents[3]
DEFAULT_OUTPUT_YAML = REPO_ROOT / "references" / "open_duck_mini" / "duck_robot_parameters.yaml"
DEFAULT_REPORT = REPO_ROOT / "references" / "open_duck_mini" / "duck_extraction_report.md"
DEFAULT_MANIFEST = REPO_ROOT / "references" / "open_duck_mini" / "source_manifest.yaml"


def build_parser() -> argparse.ArgumentParser:
    """Build the CLI parser."""

    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("--duck-xml", type=Path, required=True, help="Open Duck Mini MuJoCo XML path.")
    parser.add_argument("--output-yaml", type=Path, default=DEFAULT_OUTPUT_YAML)
    parser.add_argument("--report", type=Path, default=DEFAULT_REPORT)
    parser.add_argument("--source-manifest", type=Path, default=DEFAULT_MANIFEST)
    return parser


def write_report(path: Path, parameters: dict[str, Any], output_yaml: Path) -> None:
    """Write a compact Duck extraction report."""

    counts = parameters["counts"]
    summary = parameters["summary"]
    lines = [
        "# Open Duck Mini Extraction Report",
        "",
        "Generated by `tools.sedon.extractors.extract_duck_parameters`.",
        "",
        "## Source",
        "",
        f"- source_xml: `{parameters['source_xml']}`",
        f"- output_yaml: `{output_yaml}`",
        f"- extracted_at: `{parameters['extracted_at']}`",
        f"- tool_version: `{parameters['tool_version']}`",
        "",
        "## Counts",
        "",
        "| Field | Count |",
        "|---|---:|",
        f"| bodies | {counts['bodies']} |",
        f"| joints | {counts['joints']} |",
        f"| geoms | {counts['geoms']} |",
        f"| actuators | {counts['actuators']} |",
        f"| foot-related geoms | {counts['foot_related_geoms']} |",
        "",
        "## Summary",
        "",
        f"- total explicit body mass: `{summary['total_explicit_body_mass']}`",
        f"- joint types: `{summary['joint_types']}`",
        f"- geom types: `{summary['geom_types']}`",
        f"- actuator kinds: `{summary['actuator_kinds']}`",
        "",
        "## Unknown / Null Fields",
        "",
        f"- actuators without explicit kp: `{missing_field_names(parameters['actuators'], 'kp')}`",
        f"- actuators without explicit forcerange: `{missing_field_names(parameters['actuators'], 'forcerange')}`",
        "- Missing source attributes are represented as `null` in the YAML snapshot.",
        "",
        "## Safety Note",
        "",
        "Duck parameters are reference data for gait analysis. Do not directly copy Duck joint angles, actuator gains, or action scales into Sedon without a separate validation step.",
    ]
    path.parent.mkdir(parents=True, exist_ok=True)
    path.write_text("\n".join(lines) + "\n", encoding="utf-8")


def write_manifest(path: Path, duck_xml: Path, output_yaml: Path, report: Path, note: str) -> None:
    """Write Duck source manifest."""

    payload = {
        "schema_version": 1,
        "tool_version": TOOL_VERSION,
        "duck_xml_source_path": str(duck_xml),
        "last_extracted_at": utc_now_iso(),
        "output_yaml": str(output_yaml),
        "report": str(report),
        "notes": note,
    }
    write_yaml_compatible_json(path, payload)


def main(argv: list[str] | None = None) -> int:
    """Run Duck parameter extraction."""

    args = build_parser().parse_args(argv)
    if not args.duck_xml.is_file():
        print(f"Duck parameter extraction failed: Duck XML not found: {args.duck_xml}")
        print("Pass a valid MuJoCo XML path with --duck-xml <path>.")
        return 2

    try:
        parameters = extract_robot_parameters(args.duck_xml, "open_duck_mini")
        write_yaml_compatible_json(args.output_yaml, parameters)
        write_report(args.report, parameters, args.output_yaml)
        write_manifest(
            args.source_manifest,
            args.duck_xml,
            args.output_yaml,
            args.report,
            "Generated from the provided Duck MuJoCo XML. Verify source license and version before using as a reference.",
        )
    except ExtractionError as exc:
        print(f"Duck parameter extraction failed: {exc}")
        return 2

    counts = parameters["counts"]
    print(f"wrote_yaml={args.output_yaml}")
    print(f"wrote_report={args.report}")
    print(f"wrote_manifest={args.source_manifest}")
    print(
        "duck_counts bodies={bodies} joints={joints} geoms={geoms} actuators={actuators} foot_geoms={foot_geoms}".format(
            bodies=counts["bodies"],
            joints=counts["joints"],
            geoms=counts["geoms"],
            actuators=counts["actuators"],
            foot_geoms=counts["foot_related_geoms"],
        )
    )
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
