"""Audit execution of one IK lift candidate inside the dynamic PD loop."""

from __future__ import annotations

import argparse
import csv
from dataclasses import dataclass
from pathlib import Path
from typing import Any

import mujoco
import numpy as np

from sedon_baseline.env import SedonStandingEnv
from tools.audit_sedon_shuffle_v0 import _load_config
from tools.blue_unload_mechanism_search import JOINT_NAMES, REPO_ROOT, _contact_state
from tools.ik_lift_dynamic_validation_v1 import DEFAULT_OUT_DIR as IK_VALIDATION_OUT_DIR


DEFAULT_TOP_CSV = IK_VALIDATION_OUT_DIR / "ik_lift_dynamic_validation_v1_top10.csv"
DEFAULT_OUT_DIR = REPO_ROOT / "artifacts" / "sedon_debug" / "lift_execution_audit_v1"
MAPPED_JOINTS = (
    "R_joint_hip_pitch",
    "R_joint_knee_pitch",
    "R_joint_ankle_pitch",
    "L_joint_hip_pitch",
    "L_joint_knee_pitch",
    "L_joint_ankle_pitch",
)


@dataclass(frozen=True)
class CandidateSource:
    """Resolved source candidate from the IK validation top-k CSV.

    Args:
        candidate_id: Human-readable candidate identifier.
        config_path: Reward config generated by ``ik_lift_dynamic_validation_v1``.
        seed_path: Reference seed generated by ``ik_lift_dynamic_validation_v1``.
    """

    candidate_id: str
    config_path: Path
    seed_path: Path


@dataclass(frozen=True)
class DiagnosisMetrics:
    """Aggregated lift-window metrics used for the final diagnosis."""

    diagnosis: str
    target_span_max: float
    actual_span_max: float
    tracking_ratio: float
    mean_abs_tracking_error: float
    max_abs_tracking_error: float
    expected_foot_z_delta: float
    actual_foot_z_delta: float
    max_clearance: float
    mean_swing_contact_force: float
    max_swing_contact_force: float
    mean_ctrl_saturation: float
    mean_force_saturation: float
    rows: int


def _read_top_candidate(path: Path, rank: int) -> CandidateSource:
    """Read one candidate row from the IK validation top-k CSV.

    Args:
        path: CSV path from ``ik_lift_dynamic_validation_v1``.
        rank: One-based row index to select.

    Returns:
        Candidate source paths.

    Raises:
        FileNotFoundError: If the CSV does not exist.
        ValueError: If rank is invalid or required columns are missing.
    """

    if rank < 1:
        raise ValueError("--candidate-rank must be >= 1")
    with path.open(newline="", encoding="utf-8-sig") as file:
        rows = list(csv.DictReader(file))
    if not rows:
        raise ValueError(f"No candidates in {path}")
    if rank > len(rows):
        raise ValueError(f"Requested rank {rank}, but {path} only has {len(rows)} rows")
    row = rows[rank - 1]
    missing = {"candidate_id", "config_path", "seed_path"} - set(row)
    if missing:
        raise ValueError(f"Missing required columns in {path}: {sorted(missing)}")
    return CandidateSource(
        candidate_id=row["candidate_id"],
        config_path=Path(row["config_path"]),
        seed_path=Path(row["seed_path"]),
    )


def _joint_positions_from_data(env: SedonStandingEnv, data: mujoco.MjData) -> np.ndarray:
    """Return actuated joint qpos values from arbitrary MuJoCo data."""

    return np.array(
        [data.qpos[env.model.jnt_qposadr[joint_id]] for joint_id in env._joint_ids],
        dtype=np.float64,
    )


def _foot_bottom_heights_from_data(env: SedonStandingEnv, data: mujoco.MjData) -> np.ndarray:
    """Return foot bottom heights for arbitrary MuJoCo data."""

    heights = []
    for geom_id in env._foot_geom_ids:
        geom_z = data.geom_xpos[geom_id][2]
        half_height = env.model.geom_size[geom_id][2]
        heights.append(float(geom_z - half_height))
    return np.array(heights, dtype=np.float64)


def _side_index(side: str) -> int:
    """Return foot index for a side label used by SedonStandingEnv."""

    if side == "right":
        return 0
    if side == "left":
        return 1
    return -1


def _expected_foot_z(env: SedonStandingEnv, target_positions: np.ndarray, swing_side: str) -> float:
    """Estimate kinematic swing-foot z if commanded joint targets were reached.

    The copy keeps the current floating-base pose and replaces only actuated
    joint qpos values before ``mj_forward``. This isolates target-to-foot-z
    geometry without disturbing the live rollout.
    """

    swing_index = _side_index(swing_side)
    if swing_index < 0:
        return float("nan")
    temp_data = mujoco.MjData(env.model)
    temp_data.qpos[:] = env.data.qpos
    temp_data.qvel[:] = env.data.qvel
    for joint_index, joint_id in enumerate(env._joint_ids):
        temp_data.qpos[env.model.jnt_qposadr[joint_id]] = target_positions[joint_index]
    mujoco.mj_forward(env.model, temp_data)
    return float(_foot_bottom_heights_from_data(env, temp_data)[swing_index])


def _actuator_force_saturation(env: SedonStandingEnv) -> np.ndarray:
    """Return per-actuator force saturation flags when force ranges are finite."""

    if not hasattr(env.model, "actuator_forcerange") or not hasattr(env.data, "actuator_force"):
        return np.zeros(env.model.nu, dtype=bool)
    force_range = np.asarray(env.model.actuator_forcerange, dtype=np.float64)
    actuator_force = np.asarray(env.data.actuator_force, dtype=np.float64)
    if force_range.shape[0] != actuator_force.shape[0] or actuator_force.size == 0:
        return np.zeros(env.model.nu, dtype=bool)
    span = np.maximum(force_range[:, 1] - force_range[:, 0], 1e-9)
    finite = np.isfinite(force_range).all(axis=1) & (span > 1e-8)
    lower = np.abs(actuator_force - force_range[:, 0])
    upper = np.abs(actuator_force - force_range[:, 1])
    return finite & (np.minimum(lower, upper) <= 0.02 * span)


def _ctrl_saturation(env: SedonStandingEnv) -> np.ndarray:
    """Return per-actuator ctrl saturation flags."""

    span = np.maximum(env._ctrl_range[:, 1] - env._ctrl_range[:, 0], 1e-9)
    lower = np.abs(env.data.ctrl - env._ctrl_range[:, 0])
    upper = np.abs(env.data.ctrl - env._ctrl_range[:, 1])
    return np.minimum(lower, upper) <= 0.02 * span


def _contact_counts(env: SedonStandingEnv, swing_side: str) -> tuple[int, int]:
    """Return total floor-foot contacts and swing-foot floor contacts."""

    swing_index = _side_index(swing_side)
    swing_geom_id = env._foot_geom_ids[swing_index] if swing_index >= 0 else None
    total = 0
    swing = 0
    for contact_index in range(env.data.ncon):
        contact = env.data.contact[contact_index]
        pair = {int(contact.geom1), int(contact.geom2)}
        if env._floor_geom_id not in pair:
            continue
        foot_hit = any(foot_id in pair for foot_id in env._foot_geom_ids)
        if not foot_hit:
            continue
        total += 1
        if swing_geom_id is not None and swing_geom_id in pair:
            swing += 1
    return total, swing


def _swing_contact_force(info: dict[str, Any], swing_side: str) -> float:
    """Return swing foot normal force from an environment info dict."""

    if swing_side == "right":
        return float(info["right_normal_force"])
    if swing_side == "left":
        return float(info["left_normal_force"])
    return 0.0


def _row_base(step: int, phase: dict[str, object], info: dict[str, Any], env: SedonStandingEnv, target: np.ndarray, expected_z: float) -> dict[str, Any]:
    """Build one audit row from the post-step dynamic state."""

    swing_side = str(phase["swing_side"])
    foot_heights = env._foot_bottom_heights()
    swing_index = _side_index(swing_side)
    support_z, swing_z = env._task_foot_bottom_heights(phase)
    actual_foot_z = float(foot_heights[swing_index]) if swing_index >= 0 else float("nan")
    total_contacts, swing_contacts = _contact_counts(env, swing_side)
    actual = env._joint_positions()
    error = target - actual
    ctrl_sat = _ctrl_saturation(env)
    force_sat = _actuator_force_saturation(env)
    actuator_force = np.asarray(getattr(env.data, "actuator_force", np.zeros(env.model.nu)), dtype=np.float64)
    row: dict[str, Any] = {
        "step": step,
        "phase_name": str(phase["phase_name"]),
        "support_side": str(phase["support_side"]),
        "swing_side": swing_side,
        "commanded_expected_foot_z": expected_z,
        "actual_foot_z": actual_foot_z,
        "actual_support_foot_z": float(support_z),
        "foot_clearance": max(0.0, float(swing_z - support_z)),
        "signed_clearance": float(swing_z - support_z),
        "swing_foot_contact_force": _swing_contact_force(info, swing_side),
        "total_contact_count": total_contacts,
        "swing_contact_count": swing_contacts,
        "contact_state": _contact_state(info),
        "base_height": float(info["base_height"]),
        "base_roll": float(info["base_roll"]),
        "base_pitch": float(info["base_pitch"]),
        "upright": float(info["upright"]),
        "ctrl_saturation_fraction": float(np.mean(ctrl_sat)),
        "force_saturation_fraction": float(np.mean(force_sat)),
    }
    for index, name in enumerate(JOINT_NAMES):
        row[f"cmd_{name}"] = float(target[index])
        row[f"qpos_{name}"] = float(actual[index])
        row[f"err_{name}"] = float(error[index])
        row[f"ctrl_{name}"] = float(env.data.ctrl[index])
        row[f"actuator_force_{name}"] = float(actuator_force[index]) if index < actuator_force.size else 0.0
        row[f"ctrl_sat_{name}"] = bool(ctrl_sat[index])
        row[f"force_sat_{name}"] = bool(force_sat[index])
    return row


def audit_lift_execution(source: CandidateSource, *, steps: int, seed: int) -> list[dict[str, Any]]:
    """Replay one IK lift candidate and collect per-step lift-window diagnostics."""

    env = SedonStandingEnv(reset_noise_scale=0.0, reward_config=_load_config(source.config_path))
    rows: list[dict[str, Any]] = []
    try:
        env.reset(seed=seed)
        for step in range(1, steps + 1):
            phase = env._task_phase_metadata()
            gait_target = env._nominal_joint_qpos + env._gait_joint_offsets()
            target = env._apply_safe_joint_target_clamps(gait_target)
            expected_z = _expected_foot_z(env, target, str(phase["swing_side"]))
            _, _, terminated, truncated, info = env.step(np.zeros(env.action_space.shape, dtype=np.float64))
            if "lift_mj" in str(phase["phase_name"]):
                rows.append(_row_base(step, phase, dict(info), env, target, expected_z))
            if terminated or truncated:
                break
    finally:
        env.close()
    return rows


def _write_rows(path: Path, rows: list[dict[str, Any]]) -> None:
    """Write audit rows to CSV."""

    path.parent.mkdir(parents=True, exist_ok=True)
    if not rows:
        path.write_text("", encoding="utf-8")
        return
    with path.open("w", newline="", encoding="utf-8") as file:
        writer = csv.DictWriter(file, fieldnames=list(rows[0].keys()))
        writer.writeheader()
        writer.writerows(rows)


def _mapped_joint_matrix(rows: list[dict[str, Any]], prefix: str) -> np.ndarray:
    """Return a rows x mapped-joints matrix for a field prefix."""

    return np.array(
        [[float(row[f"{prefix}_{name}"]) for name in MAPPED_JOINTS] for row in rows],
        dtype=np.float64,
    )


def diagnose(rows: list[dict[str, Any]]) -> DiagnosisMetrics:
    """Classify the observed lift execution failure mode.

    Returns:
        Aggregated metrics and one diagnosis label.

    Raises:
        ValueError: If no lift-window rows were recorded.
    """

    if not rows:
        raise ValueError("No lift-window rows were recorded.")
    cmd = _mapped_joint_matrix(rows, "cmd")
    qpos = _mapped_joint_matrix(rows, "qpos")
    err = cmd - qpos
    target_span = np.ptp(cmd, axis=0)
    actual_span = np.ptp(qpos, axis=0)
    target_span_max = float(np.max(target_span))
    actual_span_max = float(np.max(actual_span))
    tracking_ratio = actual_span_max / max(target_span_max, 1e-9)
    expected_z = np.array([float(row["commanded_expected_foot_z"]) for row in rows], dtype=np.float64)
    actual_z = np.array([float(row["actual_foot_z"]) for row in rows], dtype=np.float64)
    clearances = np.array([float(row["foot_clearance"]) for row in rows], dtype=np.float64)
    swing_forces = np.array([float(row["swing_foot_contact_force"]) for row in rows], dtype=np.float64)
    ctrl_saturation = np.array([float(row["ctrl_saturation_fraction"]) for row in rows], dtype=np.float64)
    force_saturation = np.array([float(row["force_saturation_fraction"]) for row in rows], dtype=np.float64)
    expected_delta = float(np.max(expected_z) - np.min(expected_z))
    actual_delta = float(np.max(actual_z) - np.min(actual_z))
    max_clearance = float(np.max(clearances))
    mean_swing_force = float(np.mean(swing_forces))
    max_swing_force = float(np.max(swing_forces))
    mean_ctrl_sat = float(np.mean(ctrl_saturation))
    mean_force_sat = float(np.mean(force_saturation))
    mean_abs_error = float(np.mean(np.abs(err)))
    max_abs_error = float(np.max(np.abs(err)))

    if mean_ctrl_sat >= 0.50 or mean_force_sat >= 0.50:
        label = "E. actuator_saturation"
    elif target_span_max > 1e-4 and tracking_ratio < 0.35:
        label = "A. PD_not_tracking"
    elif tracking_ratio >= 0.50 and max_clearance < 1e-3 and mean_swing_force > 5.0:
        label = "B. contact_constraint_blocks_lift"
    elif actual_delta >= 5e-4 and max_clearance < 1e-5:
        label = "D. clearance_metric_issue"
    elif tracking_ratio >= 0.50 and expected_delta >= 2e-4 and actual_delta < 0.35 * expected_delta:
        label = "C. mapping_dynamic_cancelled"
    else:
        label = "undetermined"

    return DiagnosisMetrics(
        diagnosis=label,
        target_span_max=target_span_max,
        actual_span_max=actual_span_max,
        tracking_ratio=tracking_ratio,
        mean_abs_tracking_error=mean_abs_error,
        max_abs_tracking_error=max_abs_error,
        expected_foot_z_delta=expected_delta,
        actual_foot_z_delta=actual_delta,
        max_clearance=max_clearance,
        mean_swing_contact_force=mean_swing_force,
        max_swing_contact_force=max_swing_force,
        mean_ctrl_saturation=mean_ctrl_sat,
        mean_force_saturation=mean_force_sat,
        rows=len(rows),
    )


def _write_diagnosis(path: Path, source: CandidateSource, metrics: DiagnosisMetrics) -> None:
    """Write a human-readable diagnosis summary."""

    lines = [
        metrics.diagnosis,
        "",
        f"candidate_id: {source.candidate_id}",
        f"config_path: {source.config_path}",
        f"seed_path: {source.seed_path}",
        f"lift_window_rows: {metrics.rows}",
        f"target_span_max: {metrics.target_span_max:.8f}",
        f"actual_span_max: {metrics.actual_span_max:.8f}",
        f"tracking_ratio: {metrics.tracking_ratio:.4f}",
        f"mean_abs_tracking_error: {metrics.mean_abs_tracking_error:.8f}",
        f"max_abs_tracking_error: {metrics.max_abs_tracking_error:.8f}",
        f"expected_foot_z_delta: {metrics.expected_foot_z_delta:.8f}",
        f"actual_foot_z_delta: {metrics.actual_foot_z_delta:.8f}",
        f"max_clearance: {metrics.max_clearance:.8f}",
        f"mean_swing_contact_force: {metrics.mean_swing_contact_force:.4f}",
        f"max_swing_contact_force: {metrics.max_swing_contact_force:.4f}",
        f"mean_ctrl_saturation: {metrics.mean_ctrl_saturation:.4f}",
        f"mean_force_saturation: {metrics.mean_force_saturation:.4f}",
    ]
    path.write_text("\n".join(lines) + "\n", encoding="utf-8")


def build_parser() -> argparse.ArgumentParser:
    """Build the command-line parser."""

    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("--top-csv", type=Path, default=DEFAULT_TOP_CSV)
    parser.add_argument("--candidate-rank", type=int, default=1)
    parser.add_argument("--out-dir", type=Path, default=DEFAULT_OUT_DIR)
    parser.add_argument("--steps", type=int, default=600)
    parser.add_argument("--seed", type=int, default=42)
    return parser


def main(argv: list[str] | None = None) -> int:
    """CLI entrypoint."""

    args = build_parser().parse_args(argv)
    source = _read_top_candidate(args.top_csv, args.candidate_rank)
    args.out_dir.mkdir(parents=True, exist_ok=True)
    rows = audit_lift_execution(source, steps=args.steps, seed=args.seed)
    csv_path = args.out_dir / f"{source.candidate_id}_lift_window.csv"
    diagnosis_path = args.out_dir / "diagnosis.txt"
    _write_rows(csv_path, rows)
    metrics = diagnose(rows)
    _write_diagnosis(diagnosis_path, source, metrics)
    print(f"candidate={source.candidate_id}")
    print(f"rows={metrics.rows}")
    print(f"diagnosis={metrics.diagnosis}")
    print(f"target_span={metrics.target_span_max:.8f} actual_span={metrics.actual_span_max:.8f} tracking_ratio={metrics.tracking_ratio:.4f}")
    print(f"expected_z_delta={metrics.expected_foot_z_delta:.8f} actual_z_delta={metrics.actual_foot_z_delta:.8f} clearance={metrics.max_clearance:.8f}")
    print(f"swing_force_mean={metrics.mean_swing_contact_force:.4f} ctrl_sat={metrics.mean_ctrl_saturation:.4f} force_sat={metrics.mean_force_saturation:.4f}")
    print(f"csv={csv_path}")
    print(f"diagnosis_file={diagnosis_path}")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
