"""Check readiness for Sedon Duck-like reference IK feasibility.

This phase does not solve IK when the task-space reference is blocked or lacks
foot-path targets. It writes a report and artifact summary that downstream
pipeline tooling can consume.
"""

from __future__ import annotations

import argparse
import json
from datetime import datetime, timezone
from pathlib import Path
from typing import Any

TOOL_VERSION = "sedon-duck-like-ik-feasibility-v1"
MANUAL_REQUIRED = "manual_required"

REPO_ROOT = Path(__file__).resolve().parents[3]
DEFAULT_REFERENCE = REPO_ROOT / "configs" / "sedon" / "sedon_duck_like_gait_reference.yaml"
DEFAULT_REPORT = REPO_ROOT / "docs" / "sedon_duck_like_ik_feasibility_report.md"
DEFAULT_ARTIFACT_DIR = REPO_ROOT / "artifacts" / "sedon_debug" / "duck_like_ik_feasibility"


def utc_now_iso() -> str:
    """Return an ISO-8601 UTC timestamp."""

    return datetime.now(timezone.utc).replace(microsecond=0).isoformat()


def load_json_yaml(path: Path) -> dict[str, Any]:
    """Load a JSON-compatible YAML file."""

    if not path.is_file():
        raise ValueError(f"Input file not found: {path}")
    with path.open("r", encoding="utf-8") as file:
        loaded = json.load(file)
    if not isinstance(loaded, dict):
        raise ValueError(f"Expected JSON object in {path}")
    return loaded


def write_json_yaml(path: Path, payload: dict[str, Any]) -> None:
    """Write JSON-compatible YAML output."""

    path.parent.mkdir(parents=True, exist_ok=True)
    with path.open("w", encoding="utf-8") as file:
        json.dump(payload, file, indent=2, sort_keys=False)
        file.write("\n")


def build_feasibility(reference: dict[str, Any], reference_path: Path) -> dict[str, Any]:
    """Build IK feasibility readiness payload."""

    reference_status = reference.get("summary", {}).get("status", "unknown")
    foot_path = reference.get("task_space_reference", {}).get("foot_path", {})
    foot_path_value = foot_path.get("value") if isinstance(foot_path, dict) else None
    blockers = list(reference.get("summary", {}).get("blockers", []))
    if foot_path_value is None and "task_space_foot_path_missing" not in blockers:
        blockers.append("task_space_foot_path_missing")

    status = "BLOCKED" if reference_status == "BLOCKED" or blockers else "NOT_RUN"
    return {
        "schema_version": 1,
        "tool_version": TOOL_VERSION,
        "generated_at": utc_now_iso(),
        "purpose": "Readiness gate for Sedon Duck-like task-space IK feasibility.",
        "sources": {
            "task_space_reference": str(reference_path),
        },
        "summary": {
            "status": status,
            "ik_solver_executed": False,
            "feasible": None,
            "blockers": blockers,
            "reason": "IK was not executed because the Duck-like task-space reference is blocked or lacks foot-path targets.",
        },
        "checks": [
            {
                "name": "reference_status",
                "value": reference_status,
                "passed": reference_status != "BLOCKED",
                "confidence": "high",
                "source": str(reference_path),
            },
            {
                "name": "foot_path_available",
                "value": foot_path_value is not None,
                "passed": foot_path_value is not None,
                "confidence": "high",
                "source": str(reference_path),
            },
            {
                "name": "ik_numeric_solve",
                "value": None,
                "passed": False,
                "confidence": MANUAL_REQUIRED,
                "source": None,
                "reason": "No numeric task-space foot path is available.",
            },
        ],
        "required_before_ik": [
            "validated task-space foot path",
            "joint sign validation",
            "Sedon contact simulation validation",
        ],
        "safety_notes": [
            "No IK success is claimed.",
            "No joint trajectory is generated.",
            "No training/eval logic is modified.",
        ],
    }


def write_report(path: Path, payload: dict[str, Any]) -> None:
    """Write the IK feasibility Markdown report."""

    path.parent.mkdir(parents=True, exist_ok=True)
    summary = payload["summary"]
    lines = [
        "# Sedon Duck-Like IK Feasibility Report",
        "",
        "Generated by `tools/sedon/gait/check_duck_like_reference_ik_feasibility.py`.",
        "",
        "## Summary",
        "",
        f"- Status: `{summary['status']}`",
        "- IK solver executed: `false`",
        "- Feasible: `unknown`",
        f"- Blockers: `{summary['blockers']}`",
        f"- Reason: {summary['reason']}",
        "",
        "## Checks",
        "",
        "| Check | Value | Passed | Confidence | Source |",
        "|---|---|---|---|---|",
    ]
    for check in payload["checks"]:
        lines.append(
            f"| `{check['name']}` | `{check.get('value')}` | `{check['passed']}` | `{check['confidence']}` | `{check.get('source')}` |"
        )
    lines.extend(["", "## Required Before IK", ""])
    for item in payload["required_before_ik"]:
        lines.append(f"- {item}")
    lines.extend(["", "## Safety Notes", ""])
    for note in payload["safety_notes"]:
        lines.append(f"- {note}")
    lines.append("")
    path.write_text("\n".join(lines), encoding="utf-8")


def parse_args() -> argparse.Namespace:
    """Parse CLI arguments."""

    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("--reference-yaml", type=Path, default=DEFAULT_REFERENCE)
    parser.add_argument("--report", type=Path, default=DEFAULT_REPORT)
    parser.add_argument("--artifact-dir", type=Path, default=DEFAULT_ARTIFACT_DIR)
    return parser.parse_args()


def main() -> int:
    """Run IK feasibility readiness check."""

    args = parse_args()
    try:
        reference = load_json_yaml(args.reference_yaml)
        payload = build_feasibility(reference, args.reference_yaml)
        args.artifact_dir.mkdir(parents=True, exist_ok=True)
        write_json_yaml(args.artifact_dir / "ik_feasibility_summary.yaml", payload)
        write_report(args.report, payload)
    except ValueError as exc:
        print(f"IK feasibility check failed: {exc}")
        return 1
    print(f"Wrote {args.artifact_dir / 'ik_feasibility_summary.yaml'}")
    print(f"Wrote {args.report}")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
