"""Run a gated scripted smoke-test readiness check for Duck-like Sedon gait.

The script only runs a MuJoCo smoke test when upstream IK feasibility is marked
feasible. Current blocked inputs produce a blocked report and artifact summary.
"""

from __future__ import annotations

import argparse
import json
from datetime import datetime, timezone
from pathlib import Path
from typing import Any

TOOL_VERSION = "sedon-duck-like-scripted-smoke-test-v1"

REPO_ROOT = Path(__file__).resolve().parents[3]
DEFAULT_IK = REPO_ROOT / "artifacts" / "sedon_debug" / "duck_like_ik_feasibility" / "ik_feasibility_summary.yaml"
DEFAULT_REPORT = REPO_ROOT / "docs" / "sedon_duck_like_scripted_smoke_test_report.md"
DEFAULT_ARTIFACT_DIR = REPO_ROOT / "artifacts" / "sedon_debug" / "duck_like_scripted_smoke_test"


def utc_now_iso() -> str:
    """Return an ISO-8601 UTC timestamp."""

    return datetime.now(timezone.utc).replace(microsecond=0).isoformat()


def load_json_yaml(path: Path) -> dict[str, Any]:
    """Load a JSON-compatible YAML file."""

    if not path.is_file():
        raise ValueError(f"Input file not found: {path}")
    with path.open("r", encoding="utf-8") as file:
        loaded = json.load(file)
    if not isinstance(loaded, dict):
        raise ValueError(f"Expected JSON object in {path}")
    return loaded


def write_json_yaml(path: Path, payload: dict[str, Any]) -> None:
    """Write JSON-compatible YAML output."""

    path.parent.mkdir(parents=True, exist_ok=True)
    with path.open("w", encoding="utf-8") as file:
        json.dump(payload, file, indent=2, sort_keys=False)
        file.write("\n")


def build_smoke_summary(ik_payload: dict[str, Any], ik_path: Path) -> dict[str, Any]:
    """Build smoke test summary from IK feasibility gate."""

    ik_summary = ik_payload.get("summary", {})
    ik_feasible = ik_summary.get("feasible") is True
    blockers = list(ik_summary.get("blockers", []))
    if not ik_feasible and "ik_feasibility_missing" not in blockers:
        blockers.append("ik_feasibility_missing")
    status = "NOT_RUN" if ik_feasible else "BLOCKED"
    return {
        "schema_version": 1,
        "tool_version": TOOL_VERSION,
        "generated_at": utc_now_iso(),
        "purpose": "Gated scripted MuJoCo smoke test for Sedon Duck-like gait readiness.",
        "sources": {
            "ik_feasibility_summary": str(ik_path),
        },
        "summary": {
            "status": status,
            "mujoco_executed": False,
            "walking_success": False,
            "blockers": blockers,
            "reason": "Smoke test was not run because IK feasibility is not available."
            if not ik_feasible
            else "IK feasibility is available; scripted smoke test implementation can run in a later pass.",
        },
        "checks": [
            {
                "name": "ik_feasible",
                "value": ik_feasible,
                "passed": ik_feasible,
                "confidence": "high",
                "source": str(ik_path),
            },
            {
                "name": "mujoco_smoke_execution",
                "value": None,
                "passed": False,
                "confidence": "manual_required",
                "source": None,
                "reason": "Blocked before simulation execution.",
            },
        ],
        "required_before_smoke_test": [
            "IK feasible task-space reference",
            "validated contact patch behavior",
            "scripted non-training controller target",
        ],
        "safety_notes": [
            "No walking success is claimed.",
            "No PPO/reward/training code is modified.",
            "No Duck joint trajectory is applied.",
        ],
    }


def write_report(path: Path, payload: dict[str, Any]) -> None:
    """Write smoke test report."""

    path.parent.mkdir(parents=True, exist_ok=True)
    summary = payload["summary"]
    lines = [
        "# Sedon Duck-Like Scripted Smoke Test Report",
        "",
        "Generated by `tools/sedon/gait/run_duck_like_scripted_smoke_test.py`.",
        "",
        "## Summary",
        "",
        f"- Status: `{summary['status']}`",
        "- MuJoCo executed: `false`",
        "- Walking success: `false`",
        f"- Blockers: `{summary['blockers']}`",
        f"- Reason: {summary['reason']}",
        "",
        "## Checks",
        "",
        "| Check | Value | Passed | Confidence | Source |",
        "|---|---|---|---|---|",
    ]
    for check in payload["checks"]:
        lines.append(
            f"| `{check['name']}` | `{check.get('value')}` | `{check['passed']}` | `{check['confidence']}` | `{check.get('source')}` |"
        )
    lines.extend(["", "## Required Before Smoke Test", ""])
    for item in payload["required_before_smoke_test"]:
        lines.append(f"- {item}")
    lines.extend(["", "## Safety Notes", ""])
    for note in payload["safety_notes"]:
        lines.append(f"- {note}")
    lines.append("")
    path.write_text("\n".join(lines), encoding="utf-8")


def parse_args() -> argparse.Namespace:
    """Parse CLI arguments."""

    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("--ik-summary", type=Path, default=DEFAULT_IK)
    parser.add_argument("--report", type=Path, default=DEFAULT_REPORT)
    parser.add_argument("--artifact-dir", type=Path, default=DEFAULT_ARTIFACT_DIR)
    return parser.parse_args()


def main() -> int:
    """Run the gated scripted smoke-test check."""

    args = parse_args()
    try:
        ik_payload = load_json_yaml(args.ik_summary)
        payload = build_smoke_summary(ik_payload, args.ik_summary)
        args.artifact_dir.mkdir(parents=True, exist_ok=True)
        write_json_yaml(args.artifact_dir / "scripted_smoke_test_summary.yaml", payload)
        write_report(args.report, payload)
    except ValueError as exc:
        print(f"Scripted smoke test check failed: {exc}")
        return 1
    print(f"Wrote {args.artifact_dir / 'scripted_smoke_test_summary.yaml'}")
    print(f"Wrote {args.report}")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
